language: node_js
node_js: 
  - "stable"
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install coveralls
cache:
  directories:
    - "node_modules"
  
after_success:
  - npm run report